version: '3'
services:
  fronted:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
        #command: sh -c 'cd todo-react && yarn start'
    command: sh -c 'yarn start'
    ports:
      - 8000:3000
    tty: true
